### ISSUE TITLE
AQL: customizable page size

### ISSUE THREAD

**Issue by alekitto** [fazland/api-platform-bundle#10]
In default processors if continuation token is enabled a default page size of 10 elements is set on the `PagerIterator`. This results in a very ugly check like

```php
$itr = $processor->handleRequest($request);
if ($itr instanceof PagerIterator) {
    $itr->setPageSize(500);
}
```

A `page_size` option passed to the processor object could be more convenient.

**Comment by massimilianobraglia** [comment]
Hey there, @alekitto!
This could be another interesting feature, like the other feature. Do you have some time to propose it in a PR? 😄
