### ISSUE TITLE
AQL: bad like comparison

### ISSUE THREAD

**Issue by alekitto** [fazland/api-platform-bundle#3]
In `DqlWalker::walkComparison` 

https://github.com/fazland/api-platform-bundle/blob/f639b5f90c10053815cf70bb2eea61859e9b9ab0/src/QueryLanguage/Walker/Doctrine/DqlWalker.php#L77

If the like operator is encountered, the field (database) value is lowercased, but the expression is not.

Probably a `strtolower` (or better a `mb_strtolower`) is missing around `$expression`.

**Comment by massimilianobraglia** [comment]
Good catch, @alekitto. Can you provide a PR for this? Otherwise I'll work on it next week.
