### ISSUE TITLE
AQL: default ordering

### ISSUE THREAD

**Issue by alekitto** [fazland/api-platform-bundle#9]
In default processors a default ordering could be provided to allow the generation of continuation tokens when the `order` query parameter is missing.

Now requests like `/resources` do not provide an `X-Continuation-Token` header in response as long as the `order=$order(field)` is missing. Providing a default ordering will fix this situation.

**Comment by massimilianobraglia** [comment]
Hey there, @alekitto!
This could be an interesting feature. Do you have some time to propose it in a PR? 😄
